name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ">=22"
      - name: Set github user
        run: git config user.email "test@example.com" && git config user.name "CI/CD - MMI"
      # ...
      - name: install dependencies
        run: npm ci
      - name: install release
        run: npm run release --ci